# Use the official Python image
FROM python:3.9-slim

#install vim to troubleshoot and all dependencies needed
RUN apt-get update &&  apt-get install -y pkg-config libmariadb-dev libmariadb-dev-compat vim \
     gcc \
     && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy the dependencies file to the working directory
COPY . .

# Install any dependencies
RUN pip install -r requirements.txt

# Make port 5001 available to the world outside this container
EXPOSE 5001

# Command to run the application
CMD ["python", "app.py"]