# 1. Use the official Node.js 16 image as a starting point
FROM node:16-alpine

#install vim to troubleshoot
RUN apk update &&  apk add vim
# 2. Set the working directory in the container to /app
WORKDIR /app

# 3. Copy the package.json and package-lock.json files into the container
COPY package*.json ./

# 4. Install the NPM dependencies for the Node.js app, including production-only dependencies
RUN npm install --save-dev nodemon

# 5. Copy the remaining project files into the container
COPY . .

# 6. Expose the port your app runs on. Change 3000 to your app's port if different.
EXPOSE 3000

# 7. Define the command to run your app using CMD
CMD ["npm", "start"]